Erp\Bundle\MasterBundle\Entity\CostItemTypeRef:
  type: entity
  table: master_costitemtyperef
  inheritanceType: JOINED
  fields:
    code:
      type: string
      length: 64
      nullable: false
    name:
      type: string
      length: 128
      nullable: false
