Erp\Bundle\MasterBundle\Entity\PersonIndividual:
  type: entity
  #repositoryClass: Erp\Bundle\MasterBundle\Infrastructure\ORM\Repository\PersonIndividualRepository
  table: master_personindividual
  inheritanceType: JOINED