Erp\Bundle\MasterBundle\Entity\ProjectBoq:
  type: entity
  #repositoryClass: Erp\Bundle\MasterBundle\Infrastructure\ORM\Repository\ProjectBoqRepository
  table: master_projectboq
  inheritanceType: JOINED
  manyToOne:
    project:
      targetEntity: Project
      joinColumn:
        name: id_master_project
        nullable: false
        onDelete: RESTRICT
      fetch: EAGER
  oneToMany:
    budgetTypes:
      targetEntity: ProjectBoqBudgetType
      cascade: ["persist", "refresh"]
      mappedBy: boq
  fields:
    boqContract:
      type: decimal
      precision: 15
      scale: 2
      nullable: false
    boqStartDate:
      type: date_immutable
      nullable: true
    boqFinishDate:
      type: date_immutable
      nullable: true